// File generated by FlutterFire CLI.
// Contains configuration for Firebase services.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default Firebase configuration options for your app
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsuZwdCWO17eJLNXljefRMI1bDU2oCcBA',
    appId: '1:1088795641453:android:5b18903677b68d957e2164',
    messagingSenderId: '1088795641453',
    projectId: 'kidview-7b938',
    storageBucket: 'kidview-7b938.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsuZwdCWO17eJLNXljefRMI1bDU2oCcBA',
    appId: '1:1088795641453:ios:5b18903677b68d957e2164',
    messagingSenderId: '1088795641453',
    projectId: 'kidview-7b938',
    storageBucket: 'kidview-7b938.firebasestorage.app',
    iosBundleId: 'com.kidview.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsuZwdCWO17eJLNXljefRMI1bDU2oCcBA',
    appId: '1:1088795641453:ios:5b18903677b68d957e2164',
    messagingSenderId: '1088795641453',
    projectId: 'kidview-7b938',
    storageBucket: 'kidview-7b938.firebasestorage.app',
    iosBundleId: 'com.kidview.app',
  );
}